name: Codestyle check
on: [push, pull_request]
jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install clang-tidy and clang-format
        run: |
          sudo apt-get install -y clang-tidy-10 clang-format-10
      - name: Run clang-tidy
        run: |
          find . -name '*.cpp' -or -name '*.hpp' | xargs clang-tidy-10 -p build
      - name: Run clang-format
        run: |
          find . -name '*.cpp' -or -name '*.hpp' | xargs clang-format-10 -style=file -i
          git diff --exit-code
