name: build and run unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install armadillo
        run: sudo apt-get install libarmadillo-dev
      - name: Build libAL
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          cd build/test
          ctest

